server:
  servlet:
    context-path: /libraryapp
  port: 5001

spring:
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/libraryapp?serverTimezone=Asia/Shanghai&useUnicode=true
    username: root
    password: mysqlmima123
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    jest:
      uris:http://localhost:9200
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      #      password: <MongoDB PASSWORD>
      database: libraryapp

    elasticsearch:
      cluster-nodes: localhost:9300
      cluster-name: elasticsearch
