server:
  servlet:
    context-path: /libraryapp
  port: 5001

spring:
  elasticsearch:
    jest:
      uris:http://localhost:9200
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: <MongoDB PASSWORD>
      database: libraryapp

    elasticsearch:
      cluster-nodes: localhost:9300
      cluster-name: elasticsearch
