server:
  servlet:
    context-path: /libraryapp
  port: 5001

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
#      password: mongodpwdVEfwrAYY5ozsz
      database: libraryapp

    elasticsearch:
      cluster-nodes: localhost:9200
      cluster-name: elasticsearch
#      client:
#        reactive:
#          username: localhost
